spring.application.name=logimascota
server.port=${SERVER_PORT:8082}

oracle.wallet.path=${ORACLE_WALLET_PATH:wallet}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@dba001_tp?TNS_ADMIN=${oracle.wallet.path}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:FULLSTACK}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Fullst4ck......}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:oracle.jdbc.OracleDriver}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

logging.level.root=INFO
logging.file.name=${LOG_FILE_NAME:logs/application.log}
